spring.application.name=GRUPITO_5

# URL DE LA BASE DE DATOS ( EN MI CASO PONER MI URL POR DEFECTO DE MI MYSQL )

spring.datasource.url=jdbc:mysql://localhost:3306/SISTEMA_FACURACION?serverTimezone=UTC

# USUARIO Y CONTRASEÑA DEL MY ( EN MI CASO USO MIS CREDENCIALES DE MI MYSQL )

spring.datasource.username=root
spring.datasource.password=123456

# DRIVER DEL MYSQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# CONFIGURACION DEL JPA Y HIBERNATE ( LA PERSISTENCIA DE JAVA)

# ES EL PUENTE ENTRE NUESTRAS CLASES JAVA Y NUESTRA BASE DE DATOS PARA GUARDAR DATOS ,ETC

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect



